CREATE USER 'root'@'%' IDENTIFIED BY '123456';
CREATE USER 'ybensell'@'%' IDENTIFIED BY '123456';

CREATE DATABASE db1;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON db1.* TO 'ybensell'@'%';
FLUSH PRIVILEGES;