version : '3'

services:
  nginx:
    container_name : nginx
    depends_on:
      - wordpress
    build: ./images/nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name : wordpress
    depends_on:
      - maria
    build : ./images/wordpress
    ports:
      - 9000:9000
    volumes:
      - wp:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=maria
      - WORDPRESS_DB_USER="ybensell"
      - WORDPRESS_DB_PASSWORD="123456"
      - WORDPRESS_DB_NAME=db1
    networks:
      - inception
    restart: unless-stopped

  maria:
    container_name : maria
    build: ./images/mariadb
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db1
      MYSQL_USER: "ybensell"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
    restart: unless-stopped
    
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db
  wp:
    name : wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/wp