version : '3'

services:
  nginx:
    container_name : nginx
    depends_on:
      - wordpress
    build: ./images/nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name : wordpress
    depends_on:
      - maria
    build : ./images/wordpress

    volumes:
      - wp:/var/www/html

    networks:
      - inception

    env_file:
      - .env
  
    restart: unless-stopped

  maria:
    container_name : maria
    build: ./images/mariadb
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
    
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db
  wp:
    name : wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/wp