FROM debian:buster

RUN apt-get update -y \
    && apt-get install nginx -y

# COPY index.html /var/www/html/
# COPY default.conf /etc/nginx/http.d
# COPY default /etc/nginx/sites-available/default

# CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
CMD ["bash"]